service: serverless-rest-api-with-dynamodb
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
frameworkVersion: ">=1.1.0 <2.50.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-two-keys
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/handler/createNote.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X

  list:
    handler: src/handler/listUserNotes.handler
    events:
      - http:
          path: todos
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X

  get:
    handler: src/handler/getNote.handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X

  update:
    handler: src/handler/updateNote.handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X

  delete:
    handler: src/handler/deleteNote.handler
    events:
      - http:
          path: todos/{id}/{userId}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X
  billing:
      handler: src/helper/billing.handler
      events:
        - http:
            path: billing
            method: post
            cors: true
            authorizer:
              arn: arn:aws:cognito-idp:eu-west-1:941845565656:userpool/eu-west-1_nwGY0Rl7X

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-resource.yml)}