Resources:
      TodosDynamoDbTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Retain
        Properties:
          AttributeDefinitions:
            -
              AttributeName: id
              AttributeType: S
            -
              AttributeName: userId
              AttributeType: S
          KeySchema:
            -
              AttributeName: userId
              KeyType: HASH
            -
              AttributeName: id
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          TableName: ${self:provider.environment.DYNAMODB_TABLE}
